### ISSUE TITLE
Add .dockerignore to speed up build

### ISSUE THREAD

**Issue by xou816** [voyages-sncf-technologies/vboard#23]
A [.dockerignore](https://docs.docker.com/engine/reference/builder/#dockerignore-file) file could be added to the frontend to speed up build time; otherwise, node_modules (among others) is uploaded to the docker context, and that takes ages :)

**Comment by Lucas-C** [comment]
I've started taking a look at this, but I'm experiencing issues with `docker-compose` that looks like https://github.com/docker/compose/issues/1607
It seems like the code for `docker-compose build` is not the same as the one behind `docker build` and behaves differently.

**Comment by Lucas-C** [comment]
My mistake, I had a typo in the filename
Done !
