### ISSUE TITLE
Dynamic scripting not enabled in Elasticsearch container

### ISSUE THREAD

**Issue by xou816** [voyages-sncf-technologies/vboard#25]
Dynamic scripting seems to be required for script executions. Otherwise pin updates do not work!
Mounting a directory with relevant conf _seems_ to work:
```{yml}
  elasticsearch:
    # ...
    volumes:
      - ./vboard-es-conf:/usr/share/elasticsearch/config
```
File `vboard-es-conf/elasticsearch.yml`:
```{yml}
script.disable_dynamic: false
```

**Comment by Lucas-C** [comment]
Nice !
We used to have this Elasticsearch config, do you think it is still relevant ?
```
cluster.name: elasticsearch
discovery.zen.ping.multicast.enabled: false
# Used for the live pin update
script.engine.groovy.inline.update: on
script.groovy.sandbox.enabled: true
```

**Comment by xou816** [comment]
I guess the latter two can replace the configuration above? No idea!

**Comment by Lucas-C** [comment]
Don't bother :)
