### ISSUE TITLE
Remove Status code in error message

### ISSUE THREAD

**Issue by Thomas-dot-G** [voyages-sncf-technologies/vboard#39]
When error occurs, a message is displayed explaining the problem with error status

For a more user friendly approch (and non technical users), the status code can be removed from the message

![image](https://user-images.githubusercontent.com/8658020/40842843-6f48bb2e-65af-11e8-9b33-502134dfc224.png)

An error message can be easily seen with this url: $vboard_url/#/profil/TDotG@oui.sncf (search a profile that does not exist)

**Comment by Lucas-C** [comment]
I improved the error messages
