### ISSUE TITLE
Filtre multilabel non fonctionnel dans l'appel au back

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/vboard#46]
Pour corriger l'issue https://github.com/voyages-sncf-technologies/vboard/issues/37, le filtre sur les labels se fait lors de la récupération des pins dans l'appel au back. Cela fonctionne avec un seul label mais pas avec plusieurs.

La solution se trouve peut-être dans la méthode ElasticSearchClient::getSearchPinsQuery.

**Comment by Lucas-C** [comment]
Merci @thomaslhostis pour avoir remonté cette limitation !

Le code à tester / corriger : https://github.com/voyages-sncf-technologies/vboard/blob/master/vboard-ws/src/main/java/com/vsct/vboard/services/ElasticSearchClient.java#L240
