### ISSUE TITLE
How to use Anonymous mode?

### ISSUE THREAD

**Issue by MaxenceG2M** [voyages-sncf-technologies/vboard#95]
Hi,

All in the title?

When VBoard is launched with docker, it's not possible to publish a new pin.

**Comment by Lucas-C** [comment]
Anonymous mode is the default mode.

What error do you see when you try to publish new pins ?

**Comment by MaxenceG2M** [comment]
Since I'm having different problems getting VBoard up and running, maybe it's "normal".

I use images on Docker Hub, like specified in README:
```
export TAG=latest
docker-compose pull
docker-compose up -d --no-build
```

All services are rolling out, but I think there's a problem with the back - see #94.

I don't have an error message, juste I can't post a new pin :)
![image](https://user-images.githubusercontent.com/4601728/74719714-dc898b00-5234-11ea-9c9c-1161fb991ae8.png)

Since I can't build the front either, see #96, I will working on other issues :)

**Comment by Lucas-C** [comment]
You should be able to get some technical information, either from your browser development console (what requests are failing) or from the backend container logs.

Since both tickets you mentioned are now closed, maybe we could schedule a call together to investigate further ?

**Comment by MaxenceG2M** [comment]
Hi!

Now that I've solved my various Docker problems, I'm well in anonymous mode and I can post pins :)
